// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_kill = "CgkI4MjH_LoEEAIQAQ"; // <GPGSID>
        public const string achievement_10_kills = "CgkI4MjH_LoEEAIQBg"; // <GPGSID>
        public const string achievement_first_death = "CgkI4MjH_LoEEAIQAg"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkI4MjH_LoEEAIQBw"; // <GPGSID>
        public const string achievement_second_boss = "CgkI4MjH_LoEEAIQBA"; // <GPGSID>
        public const string achievement_first_boss = "CgkI4MjH_LoEEAIQAw"; // <GPGSID>
        public const string achievement_finished_the_game = "CgkI4MjH_LoEEAIQBQ"; // <GPGSID>

}

